metricbeat.modules:
- module: redis
  metricsets: ["info", "keyspace"]
  enabled: true
  period: 10s

  # Redis hosts
  hosts: ["redis:6379"]

output.elasticsearch:
  hosts: ["http://elastic-container:9200"]
  index: "metricbeat-%{+yyyy.MM.dd}"

setup.template:
  name: 'metricbeat'
  pattern: 'metricbeat-*'
  enabled: false
